import { Text, View, Image as PdfImage, StyleSheet } from '@react-pdf/renderer';
import { BRAND, COMPANY } from '@/app/lib/constants';

// ============================================
// SHARED PDF COMPONENTS
// Replaces duplicated PDF header/footer in every module
// ============================================

const headerStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    borderBottom: `2px solid ${BRAND.secondary}`,
    paddingBottom: 15,
    alignItems: 'center',
  },
  logoSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logo: {
    width: 55,
    height: 55,
    marginRight: 12,
    objectFit: 'contain',
  },
  companyName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: BRAND.primary,
    marginBottom: 3,
  },
  companySub: {
    fontSize: 9,
    color: '#555',
  },
  titleSection: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  docTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: BRAND.primary,
    textTransform: 'uppercase',
  },
  docRef: {
    fontSize: 9,
    color: '#888',
    marginTop: 4,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#aaa',
    borderTop: '1px solid #eee',
    paddingTop: 10,
  },
  sectionHeader: {
    fontSize: 11,
    fontWeight: 'bold',
    color: BRAND.primary,
    marginTop: 15,
    marginBottom: 8,
    textTransform: 'uppercase',
    borderBottom: '1px solid #eee',
    paddingBottom: 4,
  },
  sectionHeaderBar: {
    backgroundColor: '#f8f9fa',
    padding: 8,
    marginTop: 15,
    marginBottom: 8,
    borderLeft: `4px solid ${BRAND.primary}`,
  },
  sectionHeaderBarText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: BRAND.primary,
    textTransform: 'uppercase',
  },
});

// ============================================
// PDF HEADER
// ============================================

interface PdfHeaderProps {
  title: string;
  refNumber?: string;
  logoSrc?: string;
}

export function PdfHeader({ title, refNumber, logoSrc }: PdfHeaderProps) {
  const src = logoSrc || (typeof window !== 'undefined' ? window.location.origin + COMPANY.logo : COMPANY.logo);

  return (
    <View style={headerStyles.header}>
      <View style={headerStyles.logoSection}>
        <PdfImage src={src} style={headerStyles.logo} />
        <View>
          <Text style={headerStyles.companyName}>{COMPANY.name}</Text>
          <Text style={headerStyles.companySub}>{COMPANY.tagline}</Text>
          <Text style={headerStyles.companySub}>{COMPANY.address}</Text>
        </View>
      </View>
      <View style={headerStyles.titleSection}>
        <Text style={headerStyles.docTitle}>{title}</Text>
        {refNumber && <Text style={headerStyles.docRef}>Ref: {refNumber}</Text>}
      </View>
    </View>
  );
}

// ============================================
// PDF FOOTER
// ============================================

interface PdfFooterProps {
  text?: string;
}

export function PdfFooter({ text }: PdfFooterProps) {
  return (
    <Text style={headerStyles.footer}>
      {text || `Generated by ${COMPANY.shortName} System`}
    </Text>
  );
}

// ============================================
// PDF SECTION HEADER
// ============================================

interface PdfSectionHeaderProps {
  title: string;
  variant?: 'line' | 'bar';
}

export function PdfSectionHeader({ title, variant = 'line' }: PdfSectionHeaderProps) {
  if (variant === 'bar') {
    return (
      <View style={headerStyles.sectionHeaderBar}>
        <Text style={headerStyles.sectionHeaderBarText}>{title}</Text>
      </View>
    );
  }
  return <Text style={headerStyles.sectionHeader}>{title}</Text>;
}

export { headerStyles as pdfSharedStyles };
