"use client";

import React, { useState, useEffect } from 'react';
import { useForm, useWatch } from 'react-hook-form';
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink, Image as PdfImage } from '@react-pdf/renderer';
import { FileText, User, Calendar, CreditCard, Plane, Download, CheckCircle } from 'lucide-react';

// --- 1. TIPE DATA (Types) ---
type VisaFormValues = {
  customerName: string;
  passportNo: string;
  visaType: string;
  provider: string;
  entryType: string;
  duration: number;
  processingTime: string;
  currency: string;
  pax: number;
  pricePerPax: number;
  notes: string;
};

// --- 2. TEMPLATE PDF (Yang akan di-download) ---
const pdfStyles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 12 },
  header: { marginBottom: 20, borderBottom: '2px solid #D97706', paddingBottom: 10 }, // Amber color
  title: { fontSize: 24, fontWeight: 'bold', color: '#D97706' },
  section: { margin: 10, padding: 10, flexGrow: 1 },
  row: { flexDirection: 'row', marginBottom: 5 },
  label: { width: 120, fontWeight: 'bold', color: '#555' },
  value: { flex: 1 },
  totalBox: { marginTop: 20, padding: 15, backgroundColor: '#FEF3C7', borderRadius: 5 }, // Amber-100
  totalText: { fontSize: 18, fontWeight: 'bold', textAlign: 'right', color: '#92400E' },
});

const VisaPdfDocument = ({ data }: { data: VisaFormValues }) => (
  <Document>
    <Page size="A4" style={pdfStyles.page}>
      <View style={pdfStyles.header}>
        <Text style={pdfStyles.title}>VISA QUOTATION</Text>
        <Text style={{fontSize: 10, color: '#666'}}>Ref: VISA-{new Date().getTime().toString().slice(-6)}</Text>
      </View>

      <View style={pdfStyles.section}>
        <Text style={{fontSize: 14, marginBottom: 10, fontWeight: 'bold'}}>Informasi Pelanggan</Text>
        <View style={pdfStyles.row}><Text style={pdfStyles.label}>Nama Group/Jemaah:</Text><Text style={pdfStyles.value}>{data.customerName}</Text></View>
        <View style={pdfStyles.row}><Text style={pdfStyles.label}>No. Paspor:</Text><Text style={pdfStyles.value}>{data.passportNo || "-"}</Text></View>
      </View>

      <View style={pdfStyles.section}>
        <Text style={{fontSize: 14, marginBottom: 10, fontWeight: 'bold'}}>Detail Visa</Text>
        <View style={pdfStyles.row}><Text style={pdfStyles.label}>Jenis Visa:</Text><Text style={pdfStyles.value}>{data.visaType}</Text></View>
        <View style={pdfStyles.row}><Text style={pdfStyles.label}>Provider:</Text><Text style={pdfStyles.value}>{data.provider}</Text></View>
        <View style={pdfStyles.row}><Text style={pdfStyles.label}>Tipe Entry:</Text><Text style={pdfStyles.value}>{data.entryType}</Text></View>
        <View style={pdfStyles.row}><Text style={pdfStyles.label}>Masa Tinggal:</Text><Text style={pdfStyles.value}>{data.duration} Hari</Text></View>
      </View>

      <View style={pdfStyles.totalBox}>
         <View style={pdfStyles.row}>
            <Text style={pdfStyles.label}>Harga Satuan:</Text>
            <Text style={pdfStyles.value}>{data.currency} {data.pricePerPax.toLocaleString()}</Text>
         </View>
         <View style={pdfStyles.row}>
            <Text style={pdfStyles.label}>Jumlah Pax:</Text>
            <Text style={pdfStyles.value}>{data.pax} Orang</Text>
         </View>
         <Text style={{ borderBottom: '1px solid #ccc', marginVertical: 5 }}></Text>
         <Text style={pdfStyles.totalText}>TOTAL: {data.currency} {(data.pricePerPax * data.pax).toLocaleString()}</Text>
      </View>
      
      <Text style={{position: 'absolute', bottom: 30, left: 40, fontSize: 10, color: '#999'}}>
        Generated by Travel Rehla System on {new Date().toLocaleDateString()}
      </Text>
    </Page>
  </Document>
);

// --- 3. KOMPONEN UTAMA HALAMAN ---
export default function VisaGeneratorPage() {
  const { register, control, formState: { errors } } = useForm<VisaFormValues>({
    defaultValues: {
      currency: 'USD',
      pax: 1,
      duration: 90,
      pricePerPax: 0,
      visaType: 'Umrah Reguler',
      entryType: 'Single Entry'
    }
  });

  // KUNCI LIVE PREVIEW: Gunakan useWatch untuk memantau perubahan data realtime
  const formValues = useWatch({ control });
  
  // State untuk hydration fix (Next.js specific)
  const [isClient, setIsClient] = useState(false);
  useEffect(() => setIsClient(true), []);

  const totalEstimate = (formValues.pricePerPax || 0) * (formValues.pax || 1);

  return (
    <div className="min-h-screen bg-gray-50 p-8 font-sans">
      <div className="max-w-7xl mx-auto">
        
        {/* Header Dashboard */}
        <div className="flex items-center gap-3 mb-8">
            <div className="p-3 bg-amber-500 rounded-lg shadow-lg shadow-amber-500/30">
                <FileText className="text-white w-6 h-6" />
            </div>
            <div>
                <h1 className="text-2xl font-bold text-gray-800">Visa Quotation Generator</h1>
                <p className="text-gray-500 text-sm">Create professional visa offers in seconds.</p>
            </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          
          {/* --- KOLOM KIRI: FORM INPUT (Admin Area) --- */}
          <div className="lg:col-span-7 space-y-6">
            
            {/* Section 1: Customer Info */}
            <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
              <div className="flex items-center gap-2 mb-4 text-amber-600">
                <User size={18} />
                <h2 className="font-semibold">1. Informasi Pelanggan</h2>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Nama Jemaah / Group</label>
                  <input {...register("customerName")} placeholder="Contoh: Bpk. Ahmad Family" className="w-full p-2.5 bg-gray-50 border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500 outline-none transition" />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">No. Paspor (Opsional)</label>
                  <input {...register("passportNo")} placeholder="X000000" className="w-full p-2.5 bg-gray-50 border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500 outline-none transition" />
                </div>
              </div>
            </div>

            {/* Section 2: Spesifikasi Visa */}
            <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
              <div className="flex items-center gap-2 mb-4 text-amber-600">
                <Plane size={18} />
                <h2 className="font-semibold">2. Spesifikasi Visa</h2>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Jenis Visa</label>
                  <select {...register("visaType")} className="w-full p-2.5 bg-gray-50 border border-gray-200 rounded-lg outline-none">
                    <option>Umrah Reguler</option>
                    <option>Umrah Plus</option>
                    <option>Tourist Visa</option>
                  </select>
                </div>
                <div>
                    <label className="block text-xs font-medium text-gray-700 mb-1">Provider (Muassasah)</label>
                    <input {...register("provider")} placeholder="Contoh: Eatmarna" className="w-full p-2.5 bg-gray-50 border border-gray-200 rounded-lg outline-none" />
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Tipe Entry</label>
                  <select {...register("entryType")} className="w-full p-2.5 bg-gray-50 border border-gray-200 rounded-lg outline-none">
                    <option>Single Entry</option>
                    <option>Multiple Entry (1 Tahun)</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Masa Tinggal (Hari)</label>
                  <input type="number" {...register("duration")} className="w-full p-2.5 bg-gray-50 border border-gray-200 rounded-lg outline-none" />
                </div>
              </div>
            </div>

            {/* Section 3: Keuangan */}
            <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
              <div className="flex items-center gap-2 mb-4 text-amber-600">
                <CreditCard size={18} />
                <h2 className="font-semibold">3. Harga & Persyaratan</h2>
              </div>
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Mata Uang</label>
                  <select {...register("currency")} className="w-full p-2.5 bg-gray-50 border border-gray-200 rounded-lg outline-none">
                    <option value="USD">USD ($)</option>
                    <option value="IDR">IDR (Rp)</option>
                    <option value="SAR">SAR (﷼)</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Jumlah Pax</label>
                  <input type="number" {...register("pax", { valueAsNumber: true })} className="w-full p-2.5 bg-gray-50 border border-gray-200 rounded-lg outline-none" />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Harga Satuan</label>
                  <input type="number" {...register("pricePerPax", { valueAsNumber: true })} className="w-full p-2.5 bg-gray-50 border border-gray-200 rounded-lg outline-none" />
                </div>
              </div>
            </div>

          </div>

          {/* --- KOLOM KANAN: LIVE PREVIEW (Sticky) --- */}
          <div className="lg:col-span-5">
            <div className="sticky top-8 space-y-6">
              
              {/* CARD 1: VISUAL PREVIEW (Digital Ticket Look) */}
              <div className="bg-white rounded-xl shadow-lg border-t-4 border-amber-500 overflow-hidden">
                <div className="bg-amber-50 px-6 py-4 border-b border-amber-100 flex justify-between items-center">
                    <h3 className="font-bold text-amber-800 flex items-center gap-2">
                        <CheckCircle size={16}/> Live Preview
                    </h3>
                    <span className="text-xs text-amber-600 bg-amber-100 px-2 py-1 rounded-full font-medium">Draft Mode</span>
                </div>
                
                <div className="p-6">
                    {/* Header Preview */}
                    <div className="flex justify-between items-start mb-6">
                        <div>
                            <p className="text-xs text-gray-400 uppercase tracking-wider">Customer</p>
                            <h2 className="text-lg font-bold text-gray-800 truncate max-w-[200px]">
                                {formValues.customerName || "Nama Jemaah..."}
                            </h2>
                            <p className="text-sm text-gray-500">{formValues.passportNo || "No Paspor: - "}</p>
                        </div>
                        <div className="text-right">
                             <p className="text-xs text-gray-400 uppercase tracking-wider">Visa Type</p>
                             <span className="inline-block bg-gray-100 text-gray-700 text-xs px-2 py-1 rounded mt-1 font-medium">
                                {formValues.visaType}
                             </span>
                        </div>
                    </div>

                    {/* Details Grid */}
                    <div className="grid grid-cols-2 gap-4 mb-6 bg-gray-50 p-4 rounded-lg">
                        <div>
                            <p className="text-xs text-gray-400">Duration</p>
                            <p className="text-sm font-semibold text-gray-700">{formValues.duration} Days</p>
                        </div>
                        <div>
                            <p className="text-xs text-gray-400">Entry</p>
                            <p className="text-sm font-semibold text-gray-700">{formValues.entryType}</p>
                        </div>
                         <div>
                            <p className="text-xs text-gray-400">Provider</p>
                            <p className="text-sm font-semibold text-gray-700">{formValues.provider || "-"}</p>
                        </div>
                         <div>
                            <p className="text-xs text-gray-400">Pax</p>
                            <p className="text-sm font-semibold text-gray-700">{formValues.pax} Org</p>
                        </div>
                    </div>

                    {/* Total Price Section */}
                    <div className="border-t border-dashed border-gray-300 pt-4 mt-2">
                        <div className="flex justify-between items-center mb-1">
                            <span className="text-sm text-gray-500">Subtotal ({formValues.pax} x {formValues.pricePerPax})</span>
                        </div>
                        <div className="flex justify-between items-end">
                            <span className="text-gray-800 font-bold text-lg">Total Estimasi</span>
                            <span className="text-2xl font-extrabold text-amber-600">
                                {formValues.currency} {totalEstimate.toLocaleString()}
                            </span>
                        </div>
                    </div>
                </div>
              </div>

              {/* CARD 2: ACTION BUTTON */}
              <div className="bg-gray-900 rounded-xl p-6 text-center shadow-xl">
                 <p className="text-gray-400 text-sm mb-4">Sudah yakin dengan data di atas?</p>
                 
                 {/* Tombol ini akan merender PDF secara rahasia dan langsung download */}
                 {isClient && (
                     <PDFDownloadLink 
                        document={<VisaPdfDocument data={formValues as VisaFormValues} />} 
                        fileName={`Quotation-${formValues.customerName || 'Visa'}.pdf`}
                    >
                        {({ blob, url, loading, error }) => (
                            <button 
                                disabled={loading}
                                className={`w-full py-3 px-4 rounded-lg font-bold flex items-center justify-center gap-2 transition-all ${
                                    loading ? 'bg-gray-700 text-gray-500' : 'bg-amber-500 hover:bg-amber-600 text-white shadow-lg shadow-amber-500/20'
                                }`}
                            >
                                {loading ? 'Generating PDF...' : (
                                    <>
                                        <Download size={20} />
                                        Download Official PDF
                                    </>
                                )}
                            </button>
                        )}
                    </PDFDownloadLink>
                 )}
              </div>

            </div>
          </div>

        </div>
      </div>
    </div>
  );
}